version: '3.8'

services:
  fastapi-app:
    image: rapkeb/prom:24  # Replace with your image name if different
    container_name: fastapi_app
    ports:
      - "8000:5001"  # Map container port 5001 to host port 5001
    networks:
      - app-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"  # Map container port 9090 to host port 9090
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml  # Mount configuration file
      - ./alert_rules.yml:/etc/prometheus/alert_rules.yml
    networks:
      - app-network

  alertmanager:
    image: prom/alertmanager:latest
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
    ports:
      - "9093:9093"
    depends_on:
      - prometheus
    networks:
      - app-network

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=your_password  # Change this to a strong password
    networks:
      - app-network

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro  # Correct socket path on macOS
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    networks:
      - app-network

volumes:
  prometheus_data:
  grafana-storage:

networks:
  app-network:
    driver: bridge
